#!/data/data/com.termux/files/usr/bin/bash

echo "=== Uninstall Debug Keyboard ==="
echo ""
echo "The signing key mismatch error occurs when:"
echo "- The installed app was signed with GitHub Actions keystore"
echo "- Your local build uses a different debug.keystore"
echo ""
echo "MANUAL UNINSTALL REQUIRED:"
echo "1. Open Settings → Apps"
echo "2. Find 'Unexpected Keyboard (Debug)'"
echo "3. Tap 'Uninstall'"
echo ""
echo "Then install the new APK:"
echo "- Open keyboard Settings → About → Install Update"
echo "- Or use: am start -a android.intent.action.VIEW -d file:///sdcard/unexpected/debug-kb.apk -t application/vnd.android.package-archive"
echo ""
echo "APK Location: /sdcard/unexpected/debug-kb.apk"
echo "APK Size: $(du -h /sdcard/unexpected/debug-kb.apk 2>/dev/null | cut -f1 || echo 'not found')"
echo ""
echo "Current debug keystore fingerprint:"
keytool -list -keystore debug.keystore -storepass debug0 2>/dev/null | grep SHA256 || echo "Error reading keystore"
